name: LaTeX to PDF
on:
  push:
    paths:
      - report/**
      - "!report/main.pdf"
  workflow_dispatch:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repo
        uses: actions/checkout@v4
      - name: GitHub Action for LaTeX
        uses: xu-cheng/latex-action@v4
        with:
          root_file: Template.tex
          working_directory: ./report/
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: report-pdf
          path: ./report/main.pdf
      - name: Commit PDF to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add ./report/main.pdf
          git commit -m "Add compiled PDF"
          git push
